openapi: 3.0.3
info:
  title: Ultravox
  version: 0.1.0
  description: API for the Ultravox service.
paths:
  /api/calls:
    get:
      operationId: calls_list
      parameters:
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.
        schema:
          type: string
      tags:
      - calls
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedCallList'
          description: ''
    post:
      operationId: calls_create
      tags:
      - calls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Call'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Call'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Call'
      security:
      - apiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Call'
          description: ''
  /api/calls/{uuid}:
    get:
      operationId: calls_retrieve
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - calls
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Call'
          description: ''
    delete:
      operationId: calls_destroy
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - calls
      security:
      - apiKeyAuth: []
      responses:
        '204':
          description: No response body
  /api/calls/{uuid}/messages:
    get:
      operationId: calls_messages_list
      parameters:
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.
        schema:
          type: string
      - in: path
        name: uuid
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - calls
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMessageList'
          description: ''
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - apiKeyAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/tools:
    get:
      operationId: tools_list
      parameters:
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.
        schema:
          type: string
      tags:
      - tools
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedToolList'
          description: ''
    post:
      operationId: tools_create
      tags:
      - tools
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tool'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tool'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Tool'
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
          description: ''
  /api/voices:
    get:
      operationId: voices_list
      parameters:
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.
        schema:
          type: string
      tags:
      - voices
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedVoiceList'
          description: ''
components:
  schemas:
    Call:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        ended:
          type: string
          format: date-time
          readOnly: true
          nullable: true
        model:
          type: string
        systemPrompt:
          type: string
          nullable: true
        temperature:
          type: number
          format: double
          maximum: 1.0
          minimum: 0.0
        initialMessages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
          writeOnly: true
        availableTools:
          type: array
          items:
            $ref: '#/components/schemas/_AvailableTools'
          writeOnly: true
        voice:
          type: string
        languageHint:
          type: string
          nullable: true
          description: BCP47 language code that may be used to guide speech recognition.
          maxLength: 16
        joinUrl:
          type: string
          nullable: true
          readOnly: true
      required:
      - created
      - ended
      - joinUrl
      - uuid
    LocationEnum:
      enum:
      - path
      - query
      - header
      - body
      type: string
      description: |-
        * `path` - path
        * `query` - query
        * `header` - header
        * `body` - body
    Message:
      type: object
      properties:
        ordinal:
          type: integer
          readOnly: true
        role:
          $ref: '#/components/schemas/RoleEnum'
        text:
          type: string
          description: The message text for user and assistant messages, tool arguments
            for tool_call messages, tool results for tool_result messages.
        invocationId:
          type: string
          nullable: true
          description: The invocation ID for tool messages. Used to pair tool calls
            with their results.
        toolName:
          type: string
          nullable: true
          description: The tool name for tool messages.
      required:
      - ordinal
      - role
      - text
    PaginatedCallList:
      type: object
      required:
      - results
      properties:
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cD00ODY%3D"
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
        results:
          type: array
          items:
            $ref: '#/components/schemas/Call'
    PaginatedMessageList:
      type: object
      required:
      - results
      properties:
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cD00ODY%3D"
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
        results:
          type: array
          items:
            $ref: '#/components/schemas/Message'
    PaginatedToolList:
      type: object
      required:
      - results
      properties:
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cD00ODY%3D"
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
        results:
          type: array
          items:
            $ref: '#/components/schemas/Tool'
    PaginatedVoiceList:
      type: object
      required:
      - results
      properties:
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cD00ODY%3D"
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
        results:
          type: array
          items:
            $ref: '#/components/schemas/Voice'
    RoleEnum:
      enum:
      - USER
      - ASSISTANT
      - TOOL_CALL
      - TOOL_RESULT
      type: string
      description: |-
        * `USER` - User
        * `ASSISTANT` - Assistant
        * `TOOL_CALL` - Tool Call
        * `TOOL_RESULT` - Tool Result
    Tool:
      type: object
      properties:
        toolId:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          readOnly: true
        baseUrlPattern:
          type: string
          readOnly: true
        description:
          type: string
          nullable: true
          readOnly: true
      required:
      - baseUrlPattern
      - description
      - name
      - toolId
    Voice:
      type: object
      properties:
        name:
          type: string
          readOnly: true
        description:
          type: string
          readOnly: true
          nullable: true
        previewUrl:
          type: string
          format: uri
          readOnly: true
          nullable: true
      required:
      - description
      - name
      - previewUrl
    _AuthToken:
      type: object
      properties:
        name:
          type: string
        token:
          type: string
      required:
      - name
      - token
    _AvailableTools:
      type: object
      properties:
        tool:
          type: string
        authTokens:
          type: array
          items:
            $ref: '#/components/schemas/_AuthToken'
        parameterRestrictions:
          type: array
          items:
            $ref: '#/components/schemas/_ParameterRestriction'
        nameOverride:
          type: string
      required:
      - tool
    _ParameterRestriction:
      type: object
      properties:
        name:
          type: string
        location:
          $ref: '#/components/schemas/LocationEnum'
        value:
          type: string
          description: The value to definitively set for the parameter.
      required:
      - location
      - name
      - value
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key
servers:
- url: https://api.ultravox.ai
